# Generated by Django 5.2.7 on 2025-10-17 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('user_id', models.CharField(db_index=True, max_length=255)),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('properties', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'events',
                'indexes': [models.Index(fields=['occurred_at', 'user_id'], name='events_occurre_8a8e90_idx'), models.Index(fields=['event_type', 'occurred_at'], name='events_event_t_446764_idx')],
            },
        ),
    ]
