# Generated by Django 5.2.7 on 2025-10-17 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='user_id',
            field=models.IntegerField(db_index=True),
        ),
    ]
